[package]
name = "minecraft-modpack-downloader"
version = "0.0.1"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"
include = ["src/**/*", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
clap = { version = "4.0.19", features = ["derive"] }
color-eyre = "0.6.2"
futures-lite = "1.12.0"
indicatif = "0.17.1"
once_cell = "1.16.0"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.91"
tap = "1.0.1"
tokio = { version = "1.23.0", features = ["macros", "rt", "rt-multi-thread", "fs"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[features]
