[package]
name = "minecraft-modpack-downloader"
version = "0.0.1"
authors = ["DanSnow <dododavid006@gmail.com>"]
edition = "2018"
include = ["src/**/*", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
futures-lite = "1.12.0"
gumdrop = "0.8.0"
indicatif = "0.16.2"
once_cell = "1.8.0"
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
tokio = { version = "1.10.0", features = ["macros", "rt", "rt-multi-thread", "fs"] }
